# Generated by Django 4.2.16 on 2024-11-05 14:51

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_first_name_user_name_remove_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='123', max_length=128, region=None),
            preserve_default=False,
        ),
    ]
