# Generated by Django 4.2.16 on 2024-11-26 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
