# Generated by Django 4.2.16 on 2025-01-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_alter_author_options_alter_book_options_and_more'),
        ('users', '0010_alter_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='owned_books',
        ),
        migrations.AddField(
            model_name='user',
            name='library',
            field=models.ManyToManyField(blank=True, related_name='users_with_library', to='books.book'),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorite_books',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='books.book'),
        ),
    ]
