# Generated by Django 4.2.16 on 2025-02-17 18:50

import core.models
from django.db import migrations
import ulid

def populate_ulids(apps, schema_editor):
    models = ['User']
    for model_name in models:
        Model = apps.get_model('users', model_name)
        for obj in Model.objects.all():
            obj.new_id = str(ulid.new())
            obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_new_id'),
    ]

    operations = [
        migrations.RunPython(populate_ulids),
    ]
