# Generated by Django 4.2.16 on 2025-02-17 19:05

import core.models
from django.db import migrations
import django_ulid.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_adding_uild_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='new_id',
            field=django_ulid.models.ULIDField(default=core.models.new_ulid, editable=False, primary_key=True, serialize=False),
        ),
    ]
