# Generated by Django 4.2.16 on 2025-02-17 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_user_id_alter_user_new_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='new_id',
            new_name='id',
        ),
    ]
