# Generated by Django 4.2.16 on 2024-10-10 11:01

import books.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('date_of_birth', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('fiction', 'Fiction'), ('mystery', 'Mystery/Thriller'), ('romance', 'Romance'), ('science_fiction', 'Science Fiction'), ('fantasy', 'Fantasy'), ('non_fiction', 'Non-Fiction'), ('biography', 'Biography/Autobiography'), ('young_adult', 'Young Adult'), ('children', "Children's Books"), ('historical_fiction', 'Historical Fiction'), ('horror', 'Horror'), ('self_help', 'Self-Help'), ('graphic_novels', 'Graphic Novels'), ('poetry', 'Poetry'), ('classics', 'Classics')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('file', models.FileField(upload_to=books.models.Book.get_book_file_uploaded_path)),
                ('format', models.CharField(choices=[('PDF', 'PDF'), ('EPUB', 'EPUB'), ('MOBI', 'MOBI')], max_length=10)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('published_date', models.DateField()),
                ('download_count', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.author')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.category')),
            ],
        ),
    ]
