# Generated by Django 4.2.16 on 2024-11-26 15:18

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_author_name_author_user_author_website_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='book',
            old_name='category',
            new_name='categories',
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=books.models.Book.get_cover_image_uploaded_path),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('fiction', 'Fiction'), ('mystery', 'Mystery/Thriller'), ('romance', 'Romance'), ('science_fiction', 'Science Fiction'), ('fantasy', 'Fantasy'), ('non_fiction', 'Non-Fiction'), ('biography', 'Biography/Autobiography'), ('young_adult', 'Young Adult'), ('children', "Children's Books"), ('historical_fiction', 'Historical Fiction'), ('horror', 'Horror'), ('self_help', 'Self-Help'), ('graphic_novels', 'Graphic Novels'), ('poetry', 'Poetry'), ('classics', 'Classics')], max_length=100, unique=True),
        ),
    ]
