# Generated by Django 4.2.16 on 2024-11-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sdfsd',
            field=models.CharField(blank=True, null=True),
        ),
    ]
