# Generated by Django 4.2.16 on 2024-11-26 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_sdfsd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='sdfsd',
        ),
    ]
