# Generated by Django 4.2.16 on 2024-12-18 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_cart_cartitem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'book')},
        ),
        migrations.DeleteModel(
            name='UserBook',
        ),
    ]
