# Generated by Django 4.2.16 on 2024-12-19 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_order_stripe_session_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stripe_session_url',
        ),
    ]
