# Generated by Django 4.2.16 on 2024-12-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_remove_order_stripe_session_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_session_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
