# Generated by Django 4.2.16 on 2024-12-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_alter_author_date_of_birth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['-created', 'user']},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created', 'title']},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['-created', 'book']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created', 'name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['book']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
