# Generated by Django 4.2.16 on 2025-01-31 19:19

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_alter_author_options_alter_book_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=books.models.Author.get_author_picture_upload_path),
        ),
    ]
