# Generated by Django 4.2.16 on 2025-02-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_author_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
    ]
