# Generated by Django 4.2.16 on 2025-02-17 18:50

import core.models
from django.db import migrations
import django_ulid.models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_orderitem_created_orderitem_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='new_id',
            field=django_ulid.models.ULIDField(blank=True, default=core.models.new_ulid, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='new_id',
            field=django_ulid.models.ULIDField(blank=True, default=core.models.new_ulid, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='new_id',
            field=django_ulid.models.ULIDField(blank=True, default=core.models.new_ulid, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='new_id',
            field=django_ulid.models.ULIDField(blank=True, default=core.models.new_ulid, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='new_id',
            field=django_ulid.models.ULIDField(blank=True, default=core.models.new_ulid, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='new_id',
            field=django_ulid.models.ULIDField(blank=True, default=core.models.new_ulid, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='new_id',
            field=django_ulid.models.ULIDField(blank=True, default=core.models.new_ulid, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='new_id',
            field=django_ulid.models.ULIDField(blank=True, default=core.models.new_ulid, editable=False, null=True),
        ),
    ]
