# Generated by Django 4.2.16 on 2025-02-17 18:50

import core.models
from django.db import migrations
import ulid

def populate_ulids(apps, schema_editor):
    models = ['Author', 'Category', 'Book', 'Order', 'OrderItem', 'Review', 'Cart', 'CartItem']
    for model_name in models:
        Model = apps.get_model('books', model_name)
        for obj in Model.objects.all():
            obj.new_id = str(ulid.new())
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_author_new_id_book_new_id_cart_new_id_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_ulids),
    ]
