# Generated by Django 4.2.16 on 2025-02-17 19:05

import core.models
from django.db import migrations
import django_ulid.models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_adding_uild_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='id',
        ),
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='id',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='id',
        ),
        migrations.RemoveField(
            model_name='category',
            name='id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='id',
        ),
        migrations.AlterField(
            model_name='author',
            name='new_id',
            field=django_ulid.models.ULIDField(default=core.models.new_ulid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='new_id',
            field=django_ulid.models.ULIDField(default=core.models.new_ulid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='new_id',
            field=django_ulid.models.ULIDField(default=core.models.new_ulid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='new_id',
            field=django_ulid.models.ULIDField(default=core.models.new_ulid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='new_id',
            field=django_ulid.models.ULIDField(default=core.models.new_ulid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='new_id',
            field=django_ulid.models.ULIDField(default=core.models.new_ulid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='new_id',
            field=django_ulid.models.ULIDField(default=core.models.new_ulid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='new_id',
            field=django_ulid.models.ULIDField(default=core.models.new_ulid, editable=False, primary_key=True, serialize=False),
        ),
    ]
