# Generated by Django 4.2.16 on 2025-02-17 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_remove_author_id_remove_book_id_remove_cart_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='new_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='new_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='new_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='new_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='new_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='new_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='new_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='new_id',
            new_name='id',
        ),
    ]
